[platformio]
default_envs = sensor-01


; ============================================================
; 공통 설정
; ============================================================

[env]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    256dpi/MQTT
    bblanchon/ArduinoJson
    boschsensortec/BSEC Software Library
    adafruit/Adafruit ADS1X15
    dfrobot/DFRobot_OxygenSensor
    adafruit/Adafruit MPU6050
    adafruit/Adafruit BusIO
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit MLX90640

build_flags =
    -D MQ7_R0_OHM=0.0
    -D MQ136_R0_OHM=0.0
    -D MQ2_R0_OHM=0.0
    -D MQ7_CO_CURVE_A=99.042
    -D MQ7_CO_CURVE_B=-1.518
    -D MQ136_H2S_CURVE_A=36.737
    -D MQ136_H2S_CURVE_B=-3.536


; ============================================================
; 고정 센서 공통 베이스
; ============================================================

[env:sensor-base]

build_src_filter =
    +<sensor_node/**>
    +<drivers/**>
    +<mqtt/**>
    -<wearable_node/**>
    -<thermal_node/**>

build_flags =
    ${env.build_flags}
    -D NODE_TYPE_SENSOR


; ============================================================
; 고정 센서 01
; ============================================================

[env:sensor-01]
extends = env:sensor-base

build_flags =
    ${env:sensor-base.build_flags}
    -D NODE_ID_VALUE=\"sensor-01\"


; ============================================================
; 고정 센서 02
; ============================================================

[env:sensor-02]
extends = env:sensor-base

build_flags =
    ${env:sensor-base.build_flags}
    -D NODE_ID_VALUE=\"sensor-02\"


; ============================================================
; 고정 센서 03
; ============================================================

[env:sensor-03]
extends = env:sensor-base

build_flags =
    ${env:sensor-base.build_flags}
    -D NODE_ID_VALUE=\"sensor-03\"


; ============================================================
; 고정 센서 04
; ============================================================

[env:sensor-04]
extends = env:sensor-base

build_flags =
    ${env:sensor-base.build_flags}
    -D NODE_ID_VALUE=\"sensor-04\"


; ============================================================
; 열화상 노드
; ============================================================

[env:thermal-node]

build_src_filter =
    +<thermal_node/**>
    -<sensor_node/**>
    -<wearable_node/**>
    -<drivers/**>
    +<mqtt/**>

build_flags =
    ${env.build_flags}
    -D NODE_TYPE_THERMAL


; ============================================================
; 웨어러블 노드
; ============================================================

[env:wearable-node]

build_src_filter =
    +<wearable_node/**>
    +<drivers/**>
    +<mqtt/**>
    -<sensor_node/**>
    -<thermal_node/**>

build_flags =
    ${env.build_flags}
    -D NODE_TYPE_WEARABLE
